CREATE DATABASE plot;
CREATE USER plottyman WITH PASSWORD 'plotter123';
GRANT ALL PRIVILEGES ON DATABASE plot TO plottyman;
ALTER DATABASE plot OWNER TO plottyman;
GRANT USAGE ON SCHEMA public TO plottyman;
GRANT CREATE ON SCHEMA public to plottyman;