# Generated by Django 5.0.6 on 2024-06-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plotter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='plotter.agent'),
        ),
        migrations.AddField(
            model_name='list',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='plotter.agent'),
        ),
        migrations.AddField(
            model_name='list',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='plotter.client'),
        ),
        migrations.AddField(
            model_name='option',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='plotter.list'),
        ),
        migrations.AddField(
            model_name='option',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.property'),
        ),
    ]
