# Generated by Django 5.0.6 on 2024-06-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
            preserve_default=False,
        ),
    ]
