# Generated by Django 5.0.3 on 2024-03-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='agent',
            new_name='user',
        ),
    ]
