# Generated by Django 5.0.3 on 2024-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_remove_agent_last_login_agent_email_agent_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='notes_specials',
            field=models.TextField(blank=True, verbose_name='Notes / Specials'),
        ),
    ]
