# Generated by Django 5.0.3 on 2024-03-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_rename_agent_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='agent',
            new_name='user',
        ),
    ]
